stop pipelines

diff --git a/.github/workflows/inference_pipeline.yml b/.github/workflows/inference_pipeline.yml
--- a/.github/workflows/inference_pipeline.yml
+++ b/.github/workflows/inference_pipeline.yml
@@ -1,60 +1,60 @@
-name: inference-pipeline
-
-on:
-  schedule:
-    - cron: '30 * * * *'
-
-  workflow_dispatch:
-
-env:
-  PYTHON_VERSION: 3.9
-  POETRY_VERSION: 1.8.2
-  POETRY_URL: https://install.python-poetry.org
-
-jobs:
-
-  inference_pipeline:
-    runs-on: ubuntu-latest
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v3
-
-    - name: Cache Poetry cache
-      uses: actions/cache@v3
-      with:
-        path: ~/.cache/pypoetry
-        key: poetry-cache-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.POETRY_VERSION }}
-    
-    - name: Cache Packages
-      uses: actions/cache@v3
-      with:
-        path: ~/.local
-        key: poetry-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}
-    
-    - name: Set up Python ${{ env.PYTHON_VERSION }}
-      uses: actions/setup-python@v3
-      with:
-        python-version: ${{ env.PYTHON_VERSION }}
-    
-    - name: Install Poetry
-      run: |
-        curl -sSL ${{ env.POETRY_URL }} | python - --version ${{ env.POETRY_VERSION }}
-        echo "$HOME/.local/bin" >> $GITHUB_PATH
-    
-    - name: Install Dependencies
-      run: poetry install
-        
-    - name: Generating new batch of predictions
-      env: 
-        HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}
-        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
-        COMET_ML_API_KEY: ${{ secrets.COMET_ML_API_KEY }}
-        COMET_ML_WORKSPACE: ${{ secrets.COMET_ML_WORKSPACE }}
-        COMET_ML_PROJECT_NAME: ${{ secrets.COMET_ML_PROJECT_NAME }}
-      run: |
-        for attempt in 1 2 3; do
-          echo "Attempt $attempt of 3"
-          make inference && exit 0 || sleep 60
-        done
-        echo "All attempts failed"
-        exit 1
+#name: inference-pipeline
+#
+#on:
+#  schedule:
+#    - cron: '30 * * * *'
+#
+#  workflow_dispatch:
+#
+#env:
+#  PYTHON_VERSION: 3.9
+#  POETRY_VERSION: 1.8.2
+#  POETRY_URL: https://install.python-poetry.org
+#
+#jobs:
+#
+#  inference_pipeline:
+#    runs-on: ubuntu-latest
+#    steps:
+#    - name: Checkout
+#      uses: actions/checkout@v3
+#
+#    - name: Cache Poetry cache
+#      uses: actions/cache@v3
+#      with:
+#        path: ~/.cache/pypoetry
+#        key: poetry-cache-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.POETRY_VERSION }}
+#    
+#    - name: Cache Packages
+#      uses: actions/cache@v3
+#      with:
+#        path: ~/.local
+#        key: poetry-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}
+#    
+#    - name: Set up Python ${{ env.PYTHON_VERSION }}
+#      uses: actions/setup-python@v3
+#      with:
+#        python-version: ${{ env.PYTHON_VERSION }}
+#    
+#    - name: Install Poetry
+#      run: |
+#        curl -sSL ${{ env.POETRY_URL }} | python - --version ${{ env.POETRY_VERSION }}
+#        echo "$HOME/.local/bin" >> $GITHUB_PATH
+#    
+#    - name: Install Dependencies
+#      run: poetry install
+#        
+#    - name: Generating new batch of predictions
+#      env: 
+#        HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}
+#        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
+#        COMET_ML_API_KEY: ${{ secrets.COMET_ML_API_KEY }}
+#        COMET_ML_WORKSPACE: ${{ secrets.COMET_ML_WORKSPACE }}
+#        COMET_ML_PROJECT_NAME: ${{ secrets.COMET_ML_PROJECT_NAME }}
+#      run: |
+#        for attempt in 1 2 3; do
+#          echo "Attempt $attempt of 3"
+#          make inference && exit 0 || sleep 60
+#        done
+#        echo "All attempts failed"
+#        exit 1
